name: Update Confluence on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  update_confluence:
    if: github.event.pull_request.merged == true  # Only run if PR is merged
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get PR Commit Messages
        id: get_commits
        run: |
          echo "commit_messages<<EOF" >> $GITHUB_ENV
          git log --pretty=format:"- %s" ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update Confluence Page
        env:
          CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
          CONFLUENCE_API_KEY: ${{ secrets.CONFLUENCE_API_KEY }}
          CONFLUENCE_BASE_URL: "https://airnewn.atlassian.net/wiki"  # Replace with your Confluence base URL
          PAGE_ID: "98308" # Replace with your Confluence Page ID
        run: |
          PAYLOAD=$(jq -n \
            --arg title "Changelog Updates" \
            --arg body "${{ env.commit_messages }}" \
            '{
              "version": { "number": 2 },
              "title": $title,
              "type": "page",
              "body": { "storage": { "value": $body, "representation": "wiki" } }
            }')

          curl -X PUT \
            -u "$CONFLUENCE_USERNAME:$CONFLUENCE_API_KEY" \
            -H "Content-Type: application/json" \
            --data "$PAYLOAD" \
            "$CONFLUENCE_BASE_URL/rest/api/content/$PAGE_ID"
