name: Update Confluence Page with Commits

on:
  workflow_dispatch:

jobs:
  update-confluence:
    runs-on: ubuntu-latest
    env:
      CONFLUENCE_URL: https://airnewn.atlassian.net/wiki
      PAGE_ID: 98308
      SPACE_KEY: "~7120201888c3feda8740dea868d9a13920847a"
      PAGE_TITLE: "Changelog Updates"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate commit table HTML
        id: commits
        run: |
          echo "Generating HTML commit table..."
          REPO_NAME="${{ github.repository }}"
          {
            echo "<table><tr><th>Module Name</th><th>Commit ID</th><th>Commit Message</th><th>Commit Date & Time</th></tr>"
            git log -n 5 --pretty=format:"<tr><td>$REPO_NAME</td><td>%h</td><td>%s</td><td>%ad</td></tr>" --date=iso
            echo "</table>"
          } > table.html

      - name: Get current page version
        id: version
        run: |
          RESPONSE=$(curl -s -u "${{ secrets.CONFLUENCE_USERNAME }}:${{ secrets.CONFLUENCE_API_TOKEN }}" \
            "$CONFLUENCE_URL/rest/api/content/$PAGE_ID?expand=version")
          VERSION=$(echo "$RESPONSE" | jq '.version.number')
          echo "version=$((VERSION + 1))" >> $GITHUB_OUTPUT

      - name: Update Confluence Page
        run: |
          echo "Building JSON payload..."
          
          # Escape the HTML content
          HTML=$(jq -Rs . < table.html)

          JSON=$(cat <<EOF
          {
            "id": "$PAGE_ID",
            "type": "page",
            "title": "$PAGE_TITLE",
            "space": {
              "key": "$SPACE_KEY"
            },
            "version": {
              "number": ${{ steps.version.outputs.version }}
            },
            "body": {
              "storage": {
                "value": $HTML,
                "representation": "storage"
              }
            }
          }
          EOF
          )

          echo "$JSON" > payload.json

          echo "Updating Confluence page..."
          curl -s -X PUT "$CONFLUENCE_URL/rest/api/content/$PAGE_ID" \
            -u "${{ secrets.CONFLUENCE_USERNAME }}:${{ secrets.CONFLUENCE_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data @"payload.json"
