name: Update Confluence Changelog

on:
  push:
    branches:
      - main

jobs:
  update-confluence:
    runs-on: ubuntu-latest
    env:
      CONFLUENCE_URL: https://airnewn.atlassian.net/wiki
      PAGE_ID: 98308
      SPACE_KEY: "~7120201888c3feda8740dea868d9a13920847a"
      PAGE_TITLE: "Changelog Updates"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate HTML Table
        id: generate
        run: |
          REPO="${{ github.repository }}"
          TABLE="<table><tr><th>Module Name</th><th>Commit ID</th><th>Commit Message</th><th>Commit Date & Time</th></tr>"

          git log -n 5 --pretty=format:"<tr><td>$REPO</td><td>%h</td><td>%s</td><td>%ad</td></tr>" --date=iso >> table.html
          TABLE+=$(cat table.html)
          TABLE+="</table>"

          TABLE_ESCAPED=$(echo "$TABLE" | jq -Rs .)
          echo "table_html=$TABLE_ESCAPED" >> $GITHUB_OUTPUT

      - name: Get Current Page Version
        id: version
        run: |
          RESPONSE=$(curl -s -u "${{ secrets.CONFLUENCE_USERNAME }}:${{ secrets.CONFLUENCE_API_TOKEN }}" \
            -X GET "$CONFLUENCE_URL/rest/api/content/$PAGE_ID?expand=version")

          PAGE_VERSION=$(echo "$RESPONSE" | jq -r '.version.number')
          echo "Current version: $PAGE_VERSION"
          echo "new_version=$((PAGE_VERSION + 1))" >> $GITHUB_OUTPUT

      - name: Update Confluence Page
        run: |
          BODY=${{ steps.generate.outputs.table_html }}
          VERSION=${{ steps.version.outputs.new_version }}

          curl -s -u "${{ secrets.CONFLUENCE_USERNAME }}:${{ secrets.CONFLUENCE_API_TOKEN }}" \
            -X PUT "$CONFLUENCE_URL/rest/api/content/$PAGE_ID" \
            -H "Content-Type: application/json" \
            -d '{
              "id": "'"$PAGE_ID"'",
              "type": "page",
              "title": "'"$PAGE_TITLE"'",
              "space": { "key": "'"$SPACE_KEY"'" },
              "version": { "number": '"$VERSION"' },
              "body": {
                "storage": {
                  "value": '"$BODY"',
                  "representation": "storage"
                }
              }
            }'
