name: Update Confluence on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  update_confluence:
    if: github.event.pull_request.merged == true  # Only run if PR is merged
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full commit history

      - name: Debug PR SHAs
        run: |
          echo "Base SHA: ${{ github.event.pull_request.base.sha }}"
          echo "Head SHA: ${{ github.event.pull_request.head.sha }}"

      - name: Fetch all commits
        run: git fetch --unshallow || git fetch --all

      - name: Generate Confluence Table
        id: generate_table
        run: |
          MODULE_NAME="${{ github.repository }}"  # Extracts repo name (Module Name)
          
          # Start creating the table HTML
          echo "<table>" > confluence_table.html
          echo "<tr><th>Module Name</th><th>Commit ID</th><th>Commit Message</th><th>Commit Date & Time</th></tr>" >> confluence_table.html
          
          # Add each commit to the table
          git log --pretty=format:"<tr><td>$MODULE_NAME</td><td>%H</td><td>%s</td><td>%cd</td></tr>" --date=local ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} >> confluence_table.html
          
          # Close the table
          echo "</table>" >> confluence_table.html
          
          # Read the generated table content into an environment variable
          TABLE_CONTENT=$(cat confluence_table.html)
          echo "TABLE_CONTENT=$TABLE_CONTENT" >> $GITHUB_ENV

      - name: Update Confluence Page
        env:
          CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
          CONFLUENCE_API_KEY: ${{ secrets.CONFLUENCE_API_KEY }}
          CONFLUENCE_BASE_URL: ${{ secrets.CONFLUENCE_BASE_URL }}
          PAGE_ID: "98308" # Replace with your actual Confluence Page ID
        run: |
          PAYLOAD=$(jq -n \
            --arg title "Changelog Updates" \
            --arg body "$TABLE_CONTENT" \
            '{
              "version": { "number": 2 },
              "title": $title,
              "type": "page",
              "body": { "storage": { "value": $body, "representation": "wiki" } }
            }')

          curl -X PUT \
            -u "$CONFLUENCE_USERNAME:$CONFLUENCE_API_KEY" \
            -H "Content-Type: application/json" \
            --data "$PAYLOAD" \
            "$CONFLUENCE_BASE_URL/rest/api/content/$PAGE_ID"
