name: Update Confluence Page Simple (Basic Auth)

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  update-confluence:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      CONFLUENCE_URL: https://airnewn.atlassian.net/wiki
      PAGE_ID: "13369346"
      PAGE_TITLE: "Json"
      SPACE_KEY: "~7120201888c3feda8740dea868d9a13920847a"
      CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
      CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}

    steps:
      - name: Get current page content and version
        id: get_page
        run: |
          RESPONSE=$(curl -s -u "$CONFLUENCE_USERNAME:$CONFLUENCE_API_TOKEN" \
            "$CONFLUENCE_URL/rest/api/content/$PAGE_ID?expand=body.storage,version")

          echo "$RESPONSE" > page.json
          OLD_CONTENT=$(jq -r '.body.storage.value' page.json)
          VERSION=$(jq '.version.number' page.json)
          echo "OLD_CONTENT<<EOF" >> $GITHUB_ENV
          echo "$OLD_CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update Confluence page content
        run: |
          FINAL_CONTENT="${OLD_CONTENT}<p>Updated from GitHub Actions on $(date)</p>"

          JSON=$(jq -n \
            --arg id "$PAGE_ID" \
            --arg title "$PAGE_TITLE" \
            --arg space_key "$SPACE_KEY" \
            --argjson version $((VERSION + 1)) \
            --arg value "$FINAL_CONTENT" \
            '{
              id: $id,
              type: "page",
              title: $title,
              space: { key: $space_key },
              version: { number: $version },
              body: {
                storage: {
                  value: $value,
                  representation: "storage"
                }
              }
            }')

          echo "$JSON" > payload.json

          curl -s -X PUT "$CONFLUENCE_URL/rest/api/content/$PAGE_ID" \
            -u "$CONFLUENCE_USERNAME:$CONFLUENCE_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d @payload.json
