name: Update Confluence Changelog

on:
  push:
    branches:
      - main

jobs:
  update-confluence:
    runs-on: ubuntu-latest
    env:
      PAGE_ID: "98308" # replace with your actual page ID

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate Commit Table HTML
        run: |
          echo '<table><tr><th>Module Name</th><th>Commit ID</th><th>Commit Message</th><th>Commit Date & Time</th></tr>' > commit_table.html
          git log -n 5 --pretty=format:'<tr><td>${{ github.repository }}</td><td>%h</td><td>%s</td><td>%ad</td></tr>' --date=iso >> commit_table.html
          echo '</table>' >> commit_table.html
          TABLE_HTML=$(cat commit_table.html)
          echo "TABLE_HTML<<EOF" >> $GITHUB_ENV
          echo "$TABLE_HTML" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Get current page version
        id: version
        run: |
          RESPONSE=$(curl -s -u "${{ secrets.CONFLUENCE_USERNAME }}:${{ secrets.CONFLUENCE_API_TOKEN }}" \
            "$CONFLUENCE_URL/rest/api/content/$PAGE_ID?expand=version")
          PAGE_VERSION=$(echo "$RESPONSE" | jq '.version.number')
          echo "PAGE_VERSION=$((PAGE_VERSION + 1))" >> $GITHUB_OUTPUT

      - name: Update Confluence Page
        run: |
          NEW_VERSION=$((PAGE_VERSION + 1))

          JSON_PAYLOAD=$(jq -n \
            --arg id "$PAGE_ID" \
            --arg title "Changelog Updates" \
            --arg space_key "~7120201888c3feda8740dea868d9a13920847a" \
            --arg value "$TABLE_HTML" \
            --argjson version "$NEW_VERSION" \
            '{
              id: $id,
              type: "page",
              title: $title,
              space: { key: $space_key },
              version: { number: $version },
              body: {
                storage: {
                  value: $value,
                  representation: "storage"
                }
              }
            }')

          echo "📦 JSON Payload:"
          echo "$JSON_PAYLOAD"

          RESPONSE=$(curl -s -w "%{http_code}" -o response.txt -X PUT \
            -u "${{ secrets.CONFLUENCE_USERNAME }}:${{ secrets.CONFLUENCE_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD" \
            "${{ secrets.CONFLUENCE_URL }}/rest/api/content/${PAGE_ID}")

          STATUS=$(cat response.txt)
          echo "Confluence Response: $STATUS"
          
          if [[ "$STATUS" != 200 ]]; then
            echo "❌ Failed to update Confluence page."
            cat response.txt
            exit 1
          fi

