name: Update Confluence Page with Git Commits

on:
  push:
    branches:
      - main

jobs:
  update-confluence:
    runs-on: ubuntu-latest
    env:
      CONFLUENCE_URL: https://airnewn.atlassian.net/wiki
      PAGE_ID: "98308"
      CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
      CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate HTML Table from Git Log
        id: generate_table
        run: |
          {
            echo '<table><tr><th>Module Name</th><th>Commit ID</th><th>Commit Message</th><th>Commit Date & Time</th></tr>'
            git log -n 5 --pretty=format:'<tr><td>${{ github.repository }}</td><td>%h</td><td>%s</td><td>%ad</td></tr>' --date=iso
            echo '</table>'
          } > commit_table.html

      - name: Escape HTML for JSON
        id: escape_html
        run: |
          TABLE_HTML=$(cat commit_table.html | jq -Rs .)
          echo "TABLE_HTML=$TABLE_HTML" >> $GITHUB_ENV

      - name: Fetch Current Confluence Page Version
        id: get_version
        run: |
          AUTH=$(echo -n "$CONFLUENCE_USERNAME:$CONFLUENCE_API_TOKEN" | base64)
          RESPONSE=$(curl -s -X GET "$CONFLUENCE_URL/rest/api/content/$PAGE_ID?expand=version" \
            -H "Authorization: Basic $AUTH" \
            -H "Accept: application/json")
          VERSION=$(echo "$RESPONSE" | jq -r '.version.number')
          echo "Current page version is $VERSION"
          echo "PAGE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update Confluence Page
        run: |
          AUTH=$(echo -n "$CONFLUENCE_USERNAME:$CONFLUENCE_API_TOKEN" | base64)
          NEW_VERSION=$((PAGE_VERSION + 1))

          cat <<EOF > payload.json
          {
            "id": "$PAGE_ID",
            "type": "page",
            "title": "Changelog Updates",
            "space": { "key": "~7120201888c3feda8740dea868d9a13920847a" },
            "version": { "number": $NEW_VERSION },
            "body": {
              "storage": {
                "value": $TABLE_HTML,
                "representation": "storage"
              }
            }
          }
          EOF

          RESPONSE=$(curl -s -X PUT "$CONFLUENCE_URL/rest/api/content/$PAGE_ID" \
            -H "Authorization: Basic $AUTH" \
            -H "Content-Type: application/json" \
            --data @payload.json)

          echo "Confluence API Response: $RESPONSE"
