name: Update Confluence Page with Commits

on:
  workflow_dispatch:

jobs:
  update-confluence:
    runs-on: ubuntu-latest
    env:
      CONFLUENCE_URL: https://airnewn.atlassian.net/wiki
      PAGE_ID: 98308
      SPACE_KEY: "~7120201888c3feda8740dea868d9a13920847a"
      PAGE_TITLE: "Changelog Updates"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate commit table HTML
        id: commits
        run: |
          echo "Generating HTML commit table..."
          REPO_NAME="${{ github.repository }}"
          echo "<table><tr><th>Module Name</th><th>Commit ID</th><th>Commit Message</th><th>Commit Date & Time</th></tr>" > table.html
          git log -n 5 --pretty=format:"<tr><td>$REPO_NAME</td><td>%h</td><td>%s</td><td>%ad</td></tr>" --date=iso >> table.html
          echo "</table>" >> table.html

          # Convert table to escaped string for JSON
          TABLE=$(jq -Rs '.' < table.html)
          echo "table=$TABLE" >> $GITHUB_OUTPUT

      - name: Get current page version
        id: version
        run: |
          RESPONSE=$(curl -s -u "${{ secrets.CONFLUENCE_USERNAME }}:${{ secrets.CONFLUENCE_API_TOKEN }}" \
            "$CONFLUENCE_URL/rest/api/content/$PAGE_ID?expand=version")
          VERSION=$(echo "$RESPONSE" | jq '.version.number')
          echo "version=$((VERSION + 1))" >> $GITHUB_OUTPUT

      - name: Update Confluence Page
        run: |
          JSON=$(jq -n \
            --arg id "$PAGE_ID" \
            --arg title "Changelog Updates" \
            --arg space_key "~7120201888c3feda8740dea868d9a13920847a" \
            --arg version "$PAGE_VERSION" \
            --arg value "$TABLE_HTML" \
            '{
              id: $id,
              type: "page",
              title: $title,
              space: { key: $space_key },
              version: { number: ($version | tonumber) },
              body: {
                storage: {
                  value: $value,
                  representation: "storage"
                }
              }
            }')

          echo "$JSON" > payload.json

          curl -s -X PUT "$CONFLUENCE_URL/rest/api/content/$PAGE_ID" \
            -u "${{ secrets.CONFLUENCE_USERNAME }}:${{ secrets.CONFLUENCE_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "$JSON"
