name: Update Confluence Page withJsons

on:
  workflow_dispatch:

  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  update-confluence:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      CONFLUENCE_URL: https://airnewn.atlassian.net/wiki
      PAGE_ID: "13369346"
      PAGE_TITLE: "Json"
      SPACE_KEY: "~7120201888c3feda8740dea868d9a13920847a"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate commit table rows
        run: |
          echo "Preparing commit table..."
          HEADER="<table><tr><th>Serial</th><th>Module</th><th>Commit ID</th><th>Message</th><th>Pull Request</th><th>Author</th><th>Date</th></tr>"
          NEW_ROWS=""
          SERIAL=1

          git fetch origin main

          while read -r LINE; do
            COMMIT_ID=$(echo "$LINE" | cut -d '|' -f1)
            MESSAGE=$(echo "$LINE" | cut -d '|' -f2)
            AUTHOR=$(echo "$LINE" | cut -d '|' -f3)
            DATE=$(echo "$LINE" | cut -d '|' -f4)
            PR_LINK="https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"
            NEW_ROWS+="<tr><td>$SERIAL</td><td>${{ github.repository }}</td><td>$COMMIT_ID</td><td>$MESSAGE</td><td><a href='$PR_LINK'>$PR_LINK</a></td><td>$AUTHOR</td><td>$DATE</td></tr>"
            SERIAL=$((SERIAL + 1))
          done < <(git log --pretty=format:"%h|%s|%an|%ad" --date=iso \
            ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.merge_commit_sha }})

          echo "$HEADER$NEW_ROWS</table>" > table.html

      - name: Get current page content
        id: get_page
        run: |
          RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.CONFLUENCE_PAT }}" \
            "$CONFLUENCE_URL/rest/api/content/$PAGE_ID?expand=body.storage,version")

          echo "$RESPONSE" > page.json
          echo "OLD_CONTENT=$(jq -r '.body.storage.value' page.json)" >> $GITHUB_ENV
          echo "VERSION=$(jq '.version.number' page.json)" >> $GITHUB_ENV

      - name: Update Confluence page
        run: |
          FINAL_CONTENT="${OLD_CONTENT}<p><br/></p>$(cat table.html)"

          JSON=$(jq -n \
            --arg id "$PAGE_ID" \
            --arg title "$PAGE_TITLE" \
            --arg space_key "$SPACE_KEY" \
            --arg version "$((VERSION + 1))" \
            --arg value "$FINAL_CONTENT" \
            '{
              id: $id,
              type: "page",
              title: $title,
              space: { key: $space_key },
              version: { number: ($version | tonumber) },
              body: {
                storage: {
                  value: $value,
                  representation: "storage"
                }
              }
            }')

          echo "$JSON" > payload.json

          curl -s -X PUT "$CONFLUENCE_URL/rest/api/content/$PAGE_ID" \
            -H "Authorization: Bearer ${{ secrets.CONFLUENCE_PAT }}" \
            -H "Content-Type: application/json" \
            -d @payload.json
