name: Update Confluence with Git Commits

on:
  push:
    branches:
      - main

jobs:
  update-confluence:
    runs-on: ubuntu-latest

    env:
      CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
      CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
      CONFLUENCE_PAGE_ID: ${{ secrets.CONFLUENCE_PAGE_ID }}
      CONFLUENCE_SPACE_KEY: ${{ secrets.CONFLUENCE_SPACE_KEY }}
      CONFLUENCE_BASE_URL: ${{ secrets.CONFLUENCE_BASE_URL }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generate HTML Commit Table
        run: |
          TABLE_HTML="<table><tr><th>Module Name</th><th>Commit ID</th><th>Commit Message</th><th>Commit Date & Time</th></tr>"
          TABLE_HTML+=$(git log -n 5 --pretty=format:'<tr><td>${{ github.repository }}</td><td>%h</td><td>%s</td><td>%ad</td></tr>' --date=iso)
          TABLE_HTML+="</table>"
          echo "TABLE_HTML<<EOF" >> $GITHUB_ENV
          echo "$TABLE_HTML" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Debug ENV Vars (Safe Output)
        run: |
          echo "Checking if username is set: ${#CONFLUENCE_USERNAME}"
          echo "Checking if token is set: ${#CONFLUENCE_API_TOKEN}"


      - name: Get Current Confluence Page Version
        id: get_version
        run: |
          AUTH=$(echo -n "$CONFLUENCE_USERNAME:$CONFLUENCE_API_TOKEN" | base64)
          RESPONSE=$(curl -s -H "Authorization: Basic $AUTH" \
                          -H "Accept: application/json" \
                          "$CONFLUENCE_BASE_URL/rest/api/content/$CONFLUENCE_PAGE_ID?expand=version")
          echo "API Response: $RESPONSE"
          PAGE_VERSION=$(echo "$RESPONSE" | jq -r '.version.number')
          echo "PAGE_VERSION=$PAGE_VERSION" >> $GITHUB_ENV

      - name: Update Confluence Page
        run: |
          NEW_VERSION=$((PAGE_VERSION + 1))
          PAYLOAD=$(jq -n \
            --arg id "$CONFLUENCE_PAGE_ID" \
            --arg title "Changelog Updates" \
            --arg space "$CONFLUENCE_SPACE_KEY" \
            --arg value "$TABLE_HTML" \
            --argjson version "$NEW_VERSION" \
            '{
              id: $id,
              type: "page",
              title: $title,
              space: { key: $space },
              version: { number: $version },
              body: { storage: { value: $value, representation: "storage" } }
            }'
          )

          AUTH=$(echo -n "$CONFLUENCE_USERNAME:$CONFLUENCE_API_TOKEN" | base64)

          RESPONSE=$(curl -s -X PUT "$CONFLUENCE_BASE_URL/rest/api/content/$CONFLUENCE_PAGE_ID" \
            -H "Authorization: Basic $AUTH" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD")

          echo "🚀 API Response: $RESPONSE"
