name: Update Confluence Page from JSON File

on:
  workflow_dispatch:

jobs:
  update-confluence:
    runs-on: ubuntu-latest
    env:
      CONFLUENCE_URL: https://airnewn.atlassian.net/wiki
      PAGE_ID: "13369346"
      PAGE_TITLE: "Json"
      SPACE_KEY: "~7120201888c3feda8740dea868d9a13920847a"

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Debug file presence
        run: |
          echo "Listing all files"
          find . -type f
          echo "Contents of pages directory:"
          ls -l pages

      - name: Convert JSON to HTML Table using Python
        run: |
          python3 <<EOF
          import json

          with open("pages/Test.json") as f:
              data = json.load(f)

          users = data.get("users", [])

          html = ['<table border="1">']
          html.append("<tr><th>ID</th><th>Name</th><th>Email</th><th>Age</th><th>Active</th><th>Roles</th></tr>")
          for user in users:
              html.append(
                  f"<tr><td>{user['id']}</td><td>{user['name']}</td><td>{user['email']}</td>"
                  f"<td>{user['age']}</td><td>{str(user['isActive']).lower()}</td><td>{', '.join(user['roles'])}</td></tr>"
              )
          html.append("</table>")

          with open("table.html", "w") as f:
              f.write('\n'.join(html))
          EOF

      - name: Get current Confluence page info
        id: get_page
        run: |
          RESPONSE=$(curl -s -u "${{ secrets.CONFLUENCE_USERNAME }}:${{ secrets.CONFLUENCE_API_TOKEN }}" \
            "$CONFLUENCE_URL/rest/api/content/$PAGE_ID?expand=body.storage,version")
          echo "$RESPONSE" > page.json

          OLD_CONTENT=$(jq -r '.body.storage.value' page.json)
          VERSION=$(jq '.version.number' page.json)

          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build payload with HTML table (Python)
        run: |
          python3 <<EOF
          import json
          import os

          page_id = os.environ["PAGE_ID"]
          page_title = os.environ["PAGE_TITLE"]
          space_key = os.environ["SPACE_KEY"]
          version = int(os.environ["VERSION"])

          with open("table.html", "r", encoding="utf-8") as f:
              html_content = f.read()

          payload = {
              "id": page_id,
              "type": "page",
              "title": page_title,
              "space": {"key": space_key},
              "version": {"number": version + 1},
              "body": {
                  "storage": {
                      "value": html_content,
                      "representation": "storage"
                  }
              }
          }

          with open("payload.json", "w", encoding="utf-8") as f:
              json.dump(payload, f)
          EOF



      - name: Update Confluence page
        run: |
          curl -s -X PUT "$CONFLUENCE_URL/rest/api/content/$PAGE_ID" \
            -u "${{ secrets.CONFLUENCE_USERNAME }}:${{ secrets.CONFLUENCE_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d @payload.json
