name: Update Confluence Changelog

on:
  push:
    branches:
      - main

jobs:
  update-confluence:
    runs-on: ubuntu-latest
    env:
      CONFLUENCE_URL: https://airnewn.atlassian.net/wiki
      PAGE_ID: 98308
      CONFLUENCE_SPACE_KEY: "~7120201888c3feda8740dea868d9a13920847a"
      CONFLUENCE_TITLE: "Changelog Updates"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generate HTML Table from Git Commits
        id: generate-table
        run: |
          MODULE_NAME="${{ github.repository }}"
          TABLE_HTML="<table><tr><th>Module Name</th><th>Commit ID</th><th>Commit Message</th><th>Commit Date & Time</th></tr>"
          while IFS= read -r line; do
            TABLE_HTML+="$line"
          done < <(git log -n 5 --pretty=format:"<tr><td>$MODULE_NAME</td><td>%h</td><td>%s</td><td>%ad</td></tr>" --date=iso)
          TABLE_HTML+="</table>"
          echo "TABLE_HTML<<EOF" >> $GITHUB_ENV
          echo "$TABLE_HTML" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Get Current Confluence Page Version
        id: get-version
        run: |
          RESPONSE=$(curl -s -u "${{ secrets.CONFLUENCE_USERNAME }}:${{ secrets.CONFLUENCE_API_TOKEN }}" \
            -X GET "$CONFLUENCE_URL/rest/api/content/$PAGE_ID?expand=version")
          echo "API Response: $RESPONSE"
          VERSION=$(echo "$RESPONSE" | jq -r '.version.number')
          NEW_VERSION=$((VERSION + 1))
          echo "Current Page Version: $VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Update Confluence Page
        run: |
          curl -s -u "${{ secrets.CONFLUENCE_USERNAME }}:${{ secrets.CONFLUENCE_API_TOKEN }}" \
            -X PUT "$CONFLUENCE_URL/rest/api/content/$PAGE_ID" \
            -H 'Content-Type: application/json' \
            -d '{
              "id": "'$PAGE_ID'",
              "type": "page",
              "title": "'"$CONFLUENCE_TITLE"'",
              "space": { "key": "'"$CONFLUENCE_SPACE_KEY"'" },
              "version": { "number": '${NEW_VERSION}' },
              "body": {
                "storage": {
                  "value": "'"${TABLE_HTML//\"/\\\"}"'",
                  "representation": "storage"
                }
              }
            }'
