name: Update Confluence on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  update_confluence:
    if: github.event.pull_request.merged == true  # Only run if PR is merged
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full commit history

      - name: Debug PR SHAs
        run: |
          echo "Base SHA: ${{ github.event.pull_request.base.sha }}"
          echo "Head SHA: ${{ github.event.pull_request.head.sha }}"

      - name: Fetch all commits
        run: git fetch --unshallow || git fetch --all

      - name: Generate Confluence Table
        id: generate_table
        run: |
          MODULE_NAME="${{ github.repository }}"  # Extracts repo name (Module Name)

          # Start the table HTML
          table="<table><tr><th>Module Name</th><th>Commit ID</th><th>Commit Message</th><th>Commit Date & Time</th></tr>"

          # Add each commit to the table
          for commit in $(git log --pretty=format:"%H %s %cd" --date=local ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}); do
            COMMIT_ID=$(echo $commit | cut -d' ' -f1)
            COMMIT_MSG=$(echo $commit | cut -d' ' -f2-)
            COMMIT_DATE=$(echo $commit | cut -d' ' -f3-)
            table="$table<tr><td>$MODULE_NAME</td><td>$COMMIT_ID</td
