name: Update Confluence Page from JSON File

on:
  workflow_dispatch:

jobs:
  update-confluence:
    runs-on: ubuntu-latest
    env:
      CONFLUENCE_URL: https://airnewn.atlassian.net/wiki
      PAGE_ID: "13369346"
      PAGE_TITLE: "Json"
      SPACE_KEY: "~7120201888c3feda8740dea868d9a13920847a"

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Debug file presence
        run: |
          echo "Listing all files"
          find . -type f
          echo "Contents of pages directory:"
          ls -l pages

      - name: Convert JSON to HTML table
        id: json_to_table
        run: |
          echo "<table><tr><th>ID</th><th>Name</th><th>Email</th><th>Age</th><th>Active</th><th>Roles</th></tr>" > table.html

          jq -r '.users[] | "<tr><td>\(.id)</td><td>\(.name)</td><td>\(.email)</td><td>\(.age)</td><td>\(.isActive)</td><td>\(.roles | join(", "))</td></tr>"' pages/Test.json >> table.html

          echo "</table>" >> table.html

          # Safely export multi-line HTML into env var
          echo "TABLE_HTML<<EOF" >> $GITHUB_ENV
          cat table.html >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV


      - name: Get current Confluence page info
        id: get_page
        run: |
          RESPONSE=$(curl -s -u "${{ secrets.CONFLUENCE_USERNAME }}:${{ secrets.CONFLUENCE_API_TOKEN }}" \
            "$CONFLUENCE_URL/rest/api/content/$PAGE_ID?expand=body.storage,version")
          echo "$RESPONSE" > page.json

          # Extract current version
          VERSION=$(jq '.version.number' page.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Prepare new payload with HTML table
        id: prepare_payload
        run: |
          NEW_CONTENT="${TABLE_HTML}"

          PAYLOAD=$(jq -n \
            --arg id "$PAGE_ID" \
            --arg title "$PAGE_TITLE" \
            --arg space_key "$SPACE_KEY" \
            --argjson version $((VERSION + 1)) \
            --arg value "$NEW_CONTENT" \
            '{
              id: $id,
              type: "page",
              title: $title,
              space: { key: $space_key },
              version: { number: $version },
              body: {
                storage: {
                  value: $value,
                  representation: "storage"
                }
              }
            }')

          echo "$PAYLOAD" > payload.json

      - name: Update Confluence page
        run: |
          curl -s -X PUT "$CONFLUENCE_URL/rest/api/content/$PAGE_ID" \
            -u "${{ secrets.CONFLUENCE_USERNAME }}:${{ secrets.CONFLUENCE_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d @payload.json
