name: Update Confluence Page with Commits

on:
  workflow_dispatch:  # Allow manual trigger

  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - '**'

jobs:
  update-confluence:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      CONFLUENCE_URL: https://airnewn.atlassian.net/wiki
      SPACE_KEY: "ENG"
      PAGE_TITLE: "Changelog Updates"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get Page ID from title
        id: get_page
        run: |
          RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.CONFLUENCE_PAT }}" \
            "$CONFLUENCE_URL/rest/api/content?title=${PAGE_TITLE// /%20}&spaceKey=$SPACE_KEY")

          PAGE_ID=$(echo "$RESPONSE" | jq -r '.results[0].id')

          if [ "$PAGE_ID" = "null" ] || [ -z "$PAGE_ID" ]; then
            echo "Page not found. You must manually create the page first."
            exit 1
          fi

          echo "PAGE_ID=$PAGE_ID" >> $GITHUB_ENV

      - name: Generate commit table rows
        id: commits
        run: |
          echo "Generating HTML commit table rows..."
          REPO_NAME="${{ github.repository }}"
          PR_LINK="https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"

          git log -n 5 --pretty=format:"<tr><td></td><td>$REPO_NAME</td><td>%h</td><td>%s</td><td><a href='$PR_LINK'>$PR_LINK</a></td><td>%an</td><td>%ad</td></tr>" --date=iso > table_rows.html

      - name: Get current page content and version
        id: page
        run: |
          RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.CONFLUENCE_PAT }}" \
            "$CONFLUENCE_URL/rest/api/content/$PAGE_ID?expand=body.storage,version")

          VERSION=$(echo "$RESPONSE" | jq '.version.number')
          CONTENT=$(echo "$RESPONSE" | jq -r '.body.storage.value')

          echo "version=$((VERSION + 1))" >> $GITHUB_OUTPUT
          echo "CONTENT<<EOF" >> $GITHUB_ENV
          echo "$CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Append new commit rows or create new table
        run: |
          NEW_ROWS=$(cat table_rows.html)
          CONTENT="${{ env.CONTENT }}"

          if echo "$CONTENT" | grep -q "</table>"; then
            echo "Existing table found. Appending rows..."
            ROW_COUNT=$(echo "$CONTENT" | grep -c '<tr>')
            SERIAL=1
            UPDATED_ROWS=""
            while read -r ROW; do
              UPDATED_ROWS+=$(echo "$ROW" | sed "s|<tr><td></td>|<tr><td>$((ROW_COUNT + SERIAL - 1))</td>|")
              SERIAL=$((SERIAL + 1))
            done <<< "$NEW_ROWS"
            UPDATED_CONTENT=$(echo "$CONTENT" | sed "s|</table>|$UPDATED_ROWS</table>|")
          else
            echo "No table found. Creating new table..."
            SERIAL=1
            UPDATED_ROWS=""
            while read -r ROW; do
              UPDATED_ROWS+=$(echo "$ROW" | sed "s|<tr><td></td>|<tr><td>$SERIAL</td>|")
              SERIAL=$((SERIAL + 1))
            done <<< "$NEW_ROWS"
            UPDATED_CONTENT="<table><tr><th>Serial</th><th>Module Name</th><th>Commit ID</th><th>Commit Message</th><th>Pull Request</th><th>Commit Author</th><th>Commit Date & Time</th></tr>$UPDATED_ROWS</table>"
          fi

          JSON=$(jq -n \
            --arg id "$PAGE_ID" \
            --arg title "$PAGE_TITLE" \
            --arg space_key "$SPACE_KEY" \
            --arg version "${{ steps.page.outputs.version }}" \
            --arg value "$UPDATED_CONTENT" \
            '{
              id: $id,
              type: "page",
              title: $title,
              space: { key: $space_key },
              version: { number: ($version | tonumber) },
              body: {
                storage: {
                  value: $value,
                  representation: "storage"
                }
              }
            }')

          echo "$JSON" > payload.json

          curl -s -X PUT "$CONFLUENCE_URL/rest/api/content/$PAGE_ID" \
            -H "Authorization: Bearer ${{ secrets.CONFLUENCE_PAT }}" \
            -H "Content-Type: application/json" \
            -d @payload.json
